<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LAF" nsURI="http://www.example.org/LAF" nsPrefix="LAF">
  <eClassifiers xsi:type="ecore:EClass" name="AssessmentFact" abstract="true" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegalEntity" eSuperTypes="#//AssessmentFact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatesTo" upperBound="-1"
        eType="#//LegalEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//LegalContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalSubject" eSuperTypes="#//LegalEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performs" upperBound="-1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalObject" eSuperTypes="#//AssessmentFact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//AssessmentFact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onWith" lowerBound="1"
        upperBound="-1" eType="#//LegalObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//LegalContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="following" upperBound="-1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegalContext" eSuperTypes="#//AssessmentFact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatesTo" upperBound="-1"
        eType="#//LegalContext"/>
  </eClassifiers>
</ecore:EPackage>
